#!/bin/bash

if [ "$1" == "" ]
then
echo "You forgot an ip address"
echo "Syntax: ./ipsweep.sh 192.168.1"

else
for ip in $(seq 1 254) ; do
      ping -c 1 $1.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" & 
done
wait
fi


What ping sweep script is :
It is a script that scans a network to show active / online devices or hosts. It send a ICMP echo request to each ip on a network and when it gets a reply from that ip 
it assumes the host is online.

